[package]
name = "asm"
version = "0.1.0"
description = "Interactive assembly interpreter written in Rust"
edition = "2024"

[dependencies]
clap = { version = "4.5.38", features = ["derive"] }
ctrlc = "3.4.7"